name: Assign PR to creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_creator:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'saleor-deployments[bot]' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Assign PR to creator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          CREATOR: ${{ github.event.pull_request.user.login }}
        run: gh pr edit "$PR_URL" --add-assignee "$CREATOR"
