name: E2E staging (dispatched)
on: workflow_dispatch

jobs:
  e2e-dispatch:
    uses: ./.github/workflows/e2e.yml
    secrets:
      saleor-token: ${{ secrets.SALEOR_TOKEN }}
      op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
